# Generated by Django 4.1 on 2022-08-29 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('broker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField()),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('bedrooms', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=2, null=True)),
                ('bathrooms', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=2, null=True)),
                ('garage', models.IntegerField()),
                ('sqft', models.IntegerField()),
                ('plot_size', models.IntegerField()),
                ('photo_main', models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/')),
                ('slug', models.SlugField(max_length=200)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='broker.broker')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
    ]
