# Generated by Django 4.1 on 2022-08-30 05:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
